#! /bin/bash

##	
## Time to update those pip modules
##
## Gabriel Alves, 2017
##

opt=$1
usage="""Usage: pip-update [option]
Options:
 	pip2		Update pip2's modules
	pip3		Update pip3's modules
	pip-pypy3	Update pip-pypy3's modules"""

if [[ "$opt" = "pip2" || "$opt" = "pip3" || "$opt" = "pip-pypy3"]]
then
	for module in $( $opt list | cut -d' ' -f 1 ); do
		$opt install --upgrade $module
	done
else
	echo "$usage"
fi
